services:
  anotifier-db:
    image: postgres:17.0-alpine
    container_name: anotifier-postgres
    environment:
      POSTGRES_DB: anofitier
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports: [ "${POSTGRES_EXTERNAL_PORT}:5432" ]
    volumes:
      - anotifier-postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
volumes:
  anotifier-postgres-data: { }