telegram:
  bot:
    name: Appointment Notifier Bot
    token: { TELEGRAM_BOT_TOKEN }
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anotifier
    password: postgres
    username: postgres
